--------------------------------------------------------
--  File created - Thursday-October-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FINANCE_RECORD
--------------------------------------------------------

  CREATE TABLE "F4RAHIM"."FINANCE_RECORD" 
   (	"HEALTH_ID" NUMBER(*,0), 
	"PAYMENT_PROGRAM" VARCHAR2(20 BYTE), 
	"PRIVATE_INSURANCE" CHAR(100 BYTE), 
	"ADMISSION_DATE" DATE, 
	"DISCHARGE_DATE" DATE, 
	"STATUS_CHARGE" VARCHAR2(20 BYTE), 
	"ACCESSED_AMOUNT" VARCHAR2(10 BYTE), 
	"BILLING_ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into F4RAHIM.FINANCE_RECORD
SET DEFINE OFF;
Insert into F4RAHIM.FINANCE_RECORD (HEALTH_ID,PAYMENT_PROGRAM,PRIVATE_INSURANCE,ADMISSION_DATE,DISCHARGE_DATE,STATUS_CHARGE,ACCESSED_AMOUNT,BILLING_ADDRESS) values (712261248,'Insurance','Manulife                                                                                            ',to_date('22-09-27','RR-MM-DD'),to_date('22-09-28','RR-MM-DD'),'Pending','320$','97 Mount Billard Dr');
Insert into F4RAHIM.FINANCE_RECORD (HEALTH_ID,PAYMENT_PROGRAM,PRIVATE_INSURANCE,ADMISSION_DATE,DISCHARGE_DATE,STATUS_CHARGE,ACCESSED_AMOUNT,BILLING_ADDRESS) values (123456789,'OHIP','NA                                                                                                  ',to_date('22-10-03','RR-MM-DD'),to_date('22-10-05','RR-MM-DD'),'Paid','424$','78 Thompson St');
--------------------------------------------------------
--  DDL for Index FINANCE_RECORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F4RAHIM"."FINANCE_RECORD_PK" ON "F4RAHIM"."FINANCE_RECORD" ("HEALTH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table FINANCE_RECORD
--------------------------------------------------------

  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" ADD CONSTRAINT "FINANCE_RECORD_PK" PRIMARY KEY ("HEALTH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
 
  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" MODIFY ("HEALTH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" MODIFY ("PAYMENT_PROGRAM" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" MODIFY ("PRIVATE_INSURANCE" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" MODIFY ("ADMISSION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" MODIFY ("DISCHARGE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" MODIFY ("STATUS_CHARGE" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" MODIFY ("ACCESSED_AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."FINANCE_RECORD" MODIFY ("BILLING_ADDRESS" NOT NULL ENABLE);
