--------------------------------------------------------
--  File created - Thursday-October-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LABORATORY_RECORD
--------------------------------------------------------

  CREATE TABLE "F4RAHIM"."LABORATORY_RECORD" 
   (	"HEALTH_ID" NUMBER(*,0), 
	"LAB_RESULT" VARCHAR2(10 BYTE), 
	"ORDERING_DOCTOR" VARCHAR2(100 BYTE), 
	"MLT" VARCHAR2(100 BYTE), 
	"MEDICAL_SCANS" VARCHAR2(200 BYTE), 
	"LAB_TEST" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into F4RAHIM.LABORATORY_RECORD
SET DEFINE OFF;
Insert into F4RAHIM.LABORATORY_RECORD (HEALTH_ID,LAB_RESULT,ORDERING_DOCTOR,MLT,MEDICAL_SCANS,LAB_TEST) values (123456789,'Low Iron','Alby','Mike','Xray','Blood Test');
Insert into F4RAHIM.LABORATORY_RECORD (HEALTH_ID,LAB_RESULT,ORDERING_DOCTOR,MLT,MEDICAL_SCANS,LAB_TEST) values (712261248,'High Iron','Eraj','Ben','MRI','Blood Test');
--------------------------------------------------------
--  Constraints for Table LABORATORY_RECORD
--------------------------------------------------------

  ALTER TABLE "F4RAHIM"."LABORATORY_RECORD" MODIFY ("HEALTH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."LABORATORY_RECORD" MODIFY ("LAB_RESULT" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."LABORATORY_RECORD" MODIFY ("ORDERING_DOCTOR" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."LABORATORY_RECORD" MODIFY ("MLT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LABORATORY_RECORD
--------------------------------------------------------

  ALTER TABLE "F4RAHIM"."LABORATORY_RECORD" ADD FOREIGN KEY ("HEALTH_ID")
	  REFERENCES "F4RAHIM"."MEDICAL_RECORD" ("HEALTH_CARD_NUMBER") ENABLE;
