--------------------------------------------------------
--  File created - Thursday-October-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEDICAL_RECORD
--------------------------------------------------------

  CREATE TABLE "F4RAHIM"."MEDICAL_RECORD" 
   (	"HEALTH_CARD_NUMBER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into F4RAHIM.MEDICAL_RECORD
SET DEFINE OFF;
Insert into F4RAHIM.MEDICAL_RECORD (HEALTH_CARD_NUMBER) values (123456789);
Insert into F4RAHIM.MEDICAL_RECORD (HEALTH_CARD_NUMBER) values (712261248);
--------------------------------------------------------
--  DDL for Index SYS_C001165830
--------------------------------------------------------

  CREATE UNIQUE INDEX "F4RAHIM"."SYS_C001165830" ON "F4RAHIM"."MEDICAL_RECORD" ("HEALTH_CARD_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table MEDICAL_RECORD
--------------------------------------------------------

  ALTER TABLE "F4RAHIM"."MEDICAL_RECORD" ADD PRIMARY KEY ("HEALTH_CARD_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
