--------------------------------------------------------
--  File created - Thursday-October-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENT_PROFILE
--------------------------------------------------------

  CREATE TABLE "F4RAHIM"."PATIENT_PROFILE" 
   (	"HEALTH_CARD_NUMBER" NUMBER(10,0), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into F4RAHIM.PATIENT_PROFILE
SET DEFINE OFF;
Insert into F4RAHIM.PATIENT_PROFILE (HEALTH_CARD_NUMBER,PASSWORD) values (123456789,'Patient1');
Insert into F4RAHIM.PATIENT_PROFILE (HEALTH_CARD_NUMBER,PASSWORD) values (712261248,'Patient2');
--------------------------------------------------------
--  DDL for Index PATIENT_PROFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F4RAHIM"."PATIENT_PROFILE_PK" ON "F4RAHIM"."PATIENT_PROFILE" ("HEALTH_CARD_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table PATIENT_PROFILE
--------------------------------------------------------

  ALTER TABLE "F4RAHIM"."PATIENT_PROFILE" ADD CONSTRAINT "PATIENT_PROFILE_PK" PRIMARY KEY ("HEALTH_CARD_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
 
  ALTER TABLE "F4RAHIM"."PATIENT_PROFILE" MODIFY ("HEALTH_CARD_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."PATIENT_PROFILE" MODIFY ("PASSWORD" NOT NULL ENABLE);
