--------------------------------------------------------
--  File created - Thursday-October-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSONAL_RECORD
--------------------------------------------------------

  CREATE TABLE "F4RAHIM"."PERSONAL_RECORD" 
   (	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"LAST_NAME" VARCHAR2(30 BYTE), 
	"PATIENT_ADDRESS" VARCHAR2(400 BYTE), 
	"HEALTH_CARD_NUMBER" NUMBER, 
	"PHONE_NUMBER" NUMBER, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"AGE" NUMBER, 
	"DATE_OF_BIRTH" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into F4RAHIM.PERSONAL_RECORD
SET DEFINE OFF;
Insert into F4RAHIM.PERSONAL_RECORD (FIRST_NAME,LAST_NAME,PATIENT_ADDRESS,HEALTH_CARD_NUMBER,PHONE_NUMBER,EMAIL,AGE,DATE_OF_BIRTH) values ('Alby','Ben','67 Mount Billard Dr',123456789,4162927172,'a.ben@gmail.com',14,to_date('08-10-16','RR-MM-DD'));
Insert into F4RAHIM.PERSONAL_RECORD (FIRST_NAME,LAST_NAME,PATIENT_ADDRESS,HEALTH_CARD_NUMBER,PHONE_NUMBER,EMAIL,AGE,DATE_OF_BIRTH) values ('Eraj','Zaidi','78 Thompson St',712261248,6472719242,'ezaidi@ryerson.ca',20,to_date('22-09-30','RR-MM-DD'));
--------------------------------------------------------
--  Constraints for Table PERSONAL_RECORD
--------------------------------------------------------

  ALTER TABLE "F4RAHIM"."PERSONAL_RECORD" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."PERSONAL_RECORD" MODIFY ("LAST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."PERSONAL_RECORD" MODIFY ("PATIENT_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."PERSONAL_RECORD" MODIFY ("HEALTH_CARD_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."PERSONAL_RECORD" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."PERSONAL_RECORD" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."PERSONAL_RECORD" MODIFY ("AGE" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."PERSONAL_RECORD" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
