--------------------------------------------------------
--  File created - Thursday-October-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STAFF_PROFILE
--------------------------------------------------------

  CREATE TABLE "F4RAHIM"."STAFF_PROFILE" 
   (	"STAFF_ID" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into F4RAHIM.STAFF_PROFILE
SET DEFINE OFF;
Insert into F4RAHIM.STAFF_PROFILE (STAFF_ID,PASSWORD) values (123456789,'Staff1');
Insert into F4RAHIM.STAFF_PROFILE (STAFF_ID,PASSWORD) values (987654321,'Staff2');
--------------------------------------------------------
--  DDL for Index SYS_C001165843
--------------------------------------------------------

  CREATE UNIQUE INDEX "F4RAHIM"."SYS_C001165843" ON "F4RAHIM"."STAFF_PROFILE" ("STAFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table STAFF_PROFILE
--------------------------------------------------------

  ALTER TABLE "F4RAHIM"."STAFF_PROFILE" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "F4RAHIM"."STAFF_PROFILE" ADD PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
